=== pedrosbmartins/downtoearth/setup/schema.json
{
  "$ref": "#/definitions/Setup",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "CircleFeature": {
      "additionalProperties": false,
      "properties": {
        "bearing": {
          "type": "number"
        },
        "drawLineToRoot": {
          "type": "boolean"
        },
        "fill": {
          "$ref": "#/definitions/Fill"
        },
        "label": {
          "$ref": "#/definitions/Label"
        },
        "offset": {
          "$ref": "#/definitions/Offset"
        },
        "outline": {
          "$ref": "#/definitions/Outline"
        },
        "radiusRatio": {
          "type": "number"
        },
        "shape": {
          "const": "circle",
          "type": "string"
        }
      },
      "required": [
        "shape"
      ],
      "type": "object"
    },
    "EllipseFeature": {
      "additionalProperties": false,
      "properties": {
        "axesRatios": {
          "additionalProperties": false,
          "properties": {
            "semiMajor": {
              "type": "number"
            },
            "semiMinor": {
              "type": "number"
            }
          },
          "required": [
            "semiMajor",
            "semiMinor"
          ],
          "type": "object"
        },
        "bearing": {
          "type": "number"
        },
        "drawLineToRoot": {
          "type": "boolean"
        },
        "fill": {
          "$ref": "#/definitions/Fill"
        },
        "label": {
          "$ref": "#/definitions/Label"
        },
        "offset": {
          "$ref": "#/definitions/Offset"
        },
        "outline": {
          "$ref": "#/definitions/Outline"
        },
        "shape": {
          "const": "ellipse",
          "type": "string"
        }
      },
      "required": [
        "shape"
      ],
      "type": "object"
    },
    "Feature": {
      "anyOf": [
        {
          "$ref": "#/definitions/CircleFeature"
        },
        {
          "$ref": "#/definitions/EllipseFeature"
        }
      ]
    },
    "Fill": {
      "additionalProperties": false,
      "properties": {
        "color": {
          "type": "string"
        },
        "opacity": {
          "type": "number"
        }
      },
      "required": [
        "color"
      ],
      "type": "object"
    },
    "GroupModel": {
      "additionalProperties": false,
      "properties": {
        "bearing": {
          "type": "number"
        },
        "bearingControl": {
          "type": "boolean"
        },
        "info": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "models": {
          "items": {
            "$ref": "#/definitions/SingleModel"
          },
          "type": "array"
        },
        "offset": {
          "$ref": "#/definitions/Offset%3C%22root%22%3E"
        },
        "popup": {
          "$ref": "#/definitions/Popup"
        },
        "visible": {
          "type": "boolean"
        }
      },
      "required": [
        "label",
        "models"
      ],
      "type": "object"
    },
    "Label": {
      "additionalProperties": false,
      "properties": {
        "position": {
          "enum": [
            "center",
            "outline"
          ],
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value",
        "position"
      ],
      "type": "object"
    },
    "Model": {
      "anyOf": [
        {
          "$ref": "#/definitions/GroupModel"
        },
        {
          "$ref": "#/definitions/SingleModel"
        }
      ]
    },
    "Offset": {
      "additionalProperties": false,
      "properties": {
        "to": {
          "enum": [
            "root",
            "group"
          ],
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      },
      "required": [
        "value"
      ],
      "type": "object"
    },
    "Offset<\"root\">": {
      "additionalProperties": false,
      "properties": {
        "to": {
          "const": "root",
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      },
      "required": [
        "value"
      ],
      "type": "object"
    },
    "Outline": {
      "additionalProperties": false,
      "properties": {
        "color": {
          "type": "string"
        },
        "width": {
          "type": "number"
        }
      },
      "required": [
        "color"
      ],
      "type": "object"
    },
    "Popup": {
      "additionalProperties": false,
      "properties": {
        "content": {
          "type": "string"
        }
      },
      "required": [
        "content"
      ],
      "type": "object"
    },
    "Root": {
      "additionalProperties": false,
      "properties": {
        "bearingControl": {
          "type": "boolean"
        },
        "features": {
          "items": {
            "$ref": "#/definitions/Feature"
          },
          "type": "array"
        },
        "icon": {
          "type": "string"
        },
        "info": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "popup": {
          "$ref": "#/definitions/Popup"
        },
        "size": {
          "type": "number"
        },
        "sizePresets": {
          "items": {
            "$ref": "#/definitions/SizePreset"
          },
          "type": "array"
        },
        "visible": {
          "type": "boolean"
        }
      },
      "required": [
        "features",
        "label",
        "size",
        "sizePresets"
      ],
      "type": "object"
    },
    "Setup": {
      "additionalProperties": false,
      "properties": {
        "$schema": {
          "type": "string"
        },
        "models": {
          "items": {
            "$ref": "#/definitions/Model"
          },
          "type": "array"
        },
        "root": {
          "$ref": "#/definitions/Root"
        },
        "title": {
          "type": "string"
        },
        "unit": {
          "$ref": "#/definitions/Unit"
        }
      },
      "required": [
        "title",
        "root"
      ],
      "type": "object"
    },
    "SingleModel": {
      "additionalProperties": false,
      "properties": {
        "bearingControl": {
          "type": "boolean"
        },
        "features": {
          "items": {
            "$ref": "#/definitions/Feature"
          },
          "type": "array"
        },
        "icon": {
          "type": "string"
        },
        "info": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "popup": {
          "$ref": "#/definitions/Popup"
        },
        "size": {
          "type": "number"
        },
        "visible": {
          "type": "boolean"
        }
      },
      "required": [
        "features",
        "label",
        "size"
      ],
      "type": "object"
    },
    "SizePreset": {
      "additionalProperties": false,
      "properties": {
        "default": {
          "type": "boolean"
        },
        "km": {
          "type": "number"
        },
        "label": {
          "type": "string"
        }
      },
      "required": [
        "label",
        "km"
      ],
      "type": "object"
    },
    "Unit": {
      "additionalProperties": false,
      "properties": {
        "km": {
          "type": "number"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "km"
      ],
      "type": "object"
    }
  }
}

=== pedrosbmartins/downtoearth/setup/pluto.json
{
  "$schema": "./schema.json",
  "title": "Pluto",
  "unit": { "name": "AU", "km": 149597870.7 },
  "root": {
    "icon": "sun",
    "label": "Sun",
    "popup": { "content": "Sun" },
    "size": 0.0093,
    "features": [
      {
        "shape": "circle",
        "fill": { "color": "#fff2d1", "opacity": 0.75 },
        "outline": { "color": "rgba(0,0,0,0.25)" }
      }
    ],
    "sizePresets": [
      { "label": "1 m", "km": 0.001 },
      { "label": "10 m", "km": 0.01, "default": true },
      { "label": "100 m", "km": 0.1 },
      { "label": "1 km", "km": 1 }
    ]
  },
  "models": [
    {
      "label": "Pluto",
      "icon": "pluto",
      "size": 78.472,
      "features": [
        {
          "shape": "ellipse",
          "label": { "value": "Pluto", "position": "outline" },
          "outline": { "color": "#45331D" },
          "axesRatios": {
            "semiMajor": 0.5,
            "semiMinor": 0.4848
          }
        }
      ]
    }
  ]
}

=== pedrosbmartins/downtoearth/setup/starSizes.json
{
  "$schema": "./schema.json",
  "title": "Star Sizes",
  "unit": { "name": "AU", "km": 149597870.7 },
  "root": {
    "icon": "sun",
    "label": "Sun",
    "size": 0.0093,
    "features": [
      {
        "shape": "circle",
        "label": { "value": "Sun", "position": "center" },
        "fill": { "color": "#fff2d1", "opacity": 0.75 },
        "outline": { "color": "rgba(0,0,0,0.25)" }
      }
    ],
    "sizePresets": [
      { "label": "100 m", "km": 0.1 },
      { "label": "1 km", "km": 1, "default": true },
      { "label": "5 km", "km": 5 }
    ]
  },
  "models": [
    {
      "label": "Stars",
      "bearing": 90,
      "bearingControl": true,
      "models": [
        {
          "label": "Vega (α Lyrae)",
          "icon": "star",
          "size": 0.02197,
          "features": [
            {
              "shape": "circle",
              "label": { "value": "Vega", "position": "center" },
              "fill": { "color": "#b9c9ff", "opacity": 0.75 },
              "outline": { "color": "rgba(0,0,0,0.25)" },
              "offset": 0.0156345836
            }
          ]
        },
        {
          "label": "Deneb (α Cygni)",
          "icon": "star",
          "size": 1.88985,
          "features": [
            {
              "shape": "circle",
              "label": { "value": "Deneb", "position": "center" },
              "fill": { "color": "#c7d6ff", "opacity": 0.75 },
              "outline": { "color": "rgba(0,0,0,0.25)" },
              "offset": 0.9715430972
            }
          ]
        },
        {
          "label": "Antares A (α Scorpii)",
          "icon": "star",
          "size": 6.33053,
          "features": [
            {
              "shape": "circle",
              "label": { "value": "Antares A", "position": "center" },
              "fill": { "color": "#ffca8a", "opacity": 0.75 },
              "outline": { "color": "rgba(0,0,0,0.25)" },
              "offset": 5.0817314972
            }
          ]
        },
        {
          "label": "Betelgeuse (α Orionis)",
          "icon": "star",
          "size": 7.11253,
          "features": [
            {
              "shape": "circle",
              "label": { "value": "Betelgeuse", "position": "center" },
              "fill": { "color": "#ffca8a", "opacity": 0.75 },
              "outline": { "color": "rgba(0,0,0,0.25)" },
              "offset": 11.8032626972
            }
          ]
        },
        {
          "label": "V602 Carinae",
          "icon": "star",
          "size": 9.77508,
          "features": [
            {
              "shape": "circle",
              "label": { "value": "V602 Carinae", "position": "center" },
              "fill": { "color": "#ffbb7b", "opacity": 0.75 },
              "outline": { "color": "rgba(0,0,0,0.25)" },
              "offset": 20.2470698972
            }
          ]
        },
        {
          "label": "VY Canis Majoris",
          "icon": "star",
          "size": 13.21963,
          "features": [
            {
              "shape": "circle",
              "label": { "value": "VY Canis Majoris", "position": "center" },
              "fill": { "color": "#ffbb7b", "opacity": 0.75 },
              "outline": { "color": "rgba(0,0,0,0.25)" },
              "offset": 31.7444258972
            }
          ]
        }
      ]
    }
  ]
}

=== pedrosbmartins/downtoearth/setup/demo.json
{
  "$schema": "./schema.json",
  "title": "Demo",
  "unit": { "name": "km", "km": 1 },
  "root": {
    "label": "Root",
    "size": 2,
    "features": [
      {
        "shape": "circle",
        "outline": { "color": "green" },
        "label": { "position": "outline", "value": "Circle" }
      },
      {
        "shape": "circle",
        "radiusRatio": 0.01,
        "fill": { "color": "green" },
        "label": { "position": "outline", "value": "Circle" }
      }
    ],
    "sizePresets": [
      { "label": "1 km", "km": 1 },
      { "label": "10 km", "km": 10, "default": true },
      { "label": "300 km", "km": 300 }
    ]
  },
  "models": [
    {
      "label": "Group 1",
      "offset": 1,
      "bearing": 180,
      "models": [
        {
          "label": "Model 1",
          "size": 2,
          "features": [
            {
              "shape": "circle",
              "outline": { "color": "red" },
              "offset": 1,
              "bearing": 180
            }
          ]
        }
      ]
    }
  ]
}

=== pedrosbmartins/downtoearth/setup/alphaCentauri.json
{
  "$schema": "./schema.json",
  "title": "Alpha Centauri",
  "unit": { "name": "AU", "km": 149597870.7 },
  "root": {
    "icon": "sun",
    "label": "Sun",
    "popup": { "content": "Sun" },
    "size": 0.0093,
    "features": [
      {
        "shape": "circle",
        "fill": { "color": "#fff2d1", "opacity": 0.75 },
        "outline": { "color": "rgba(0,0,0,0.25)" }
      }
    ],
    "sizePresets": [
      { "label": "1 cm", "km": 0.00001, "default": true },
      { "label": "2 cm", "km": 0.00002 },
      { "label": "5 cm", "km": 0.00005 },
      { "label": "10 cm", "km": 0.0001 }
    ]
  },
  "models": [
    {
      "label": "α Centauri",
      "bearingControl": true,
      "bearing": 270,
      "offset": 276000,
      "models": [
        {
          "label": "α Centauri A",
          "popup": { "content": "Alpha Centauri A" },
          "size": 0.011,
          "icon": "star",
          "features": [
            {
              "shape": "circle",
              "fill": { "color": "#fff0c0" },
              "outline": { "color": "rgba(0,0,0,0.25)" },
              "drawLineToRoot": true,
              "offset": 13020
            }
          ]
        },
        {
          "label": "α Centauri B",
          "popup": { "content": "Alpha Centauri B" },
          "size": 0.008,
          "icon": "star",
          "features": [
            {
              "shape": "circle",
              "fill": { "color": "#ffeb93" },
              "outline": { "color": "rgba(0,0,0,0.25)" },
              "drawLineToRoot": true,
              "offset": 13000
            }
          ]
        },
        {
          "label": "Proxima Centauri",
          "size": 0.001,
          "popup": { "content": "Proxima Centauri" },
          "icon": "star",
          "features": [
            {
              "shape": "circle",
              "fill": { "color": "#ffc317" },
              "outline": { "color": "rgba(0,0,0,0.25)" },
              "drawLineToRoot": true
            }
          ]
        }
      ]
    }
  ]
}

=== pedrosbmartins/downtoearth/setup/demo-single-model-multiple-layers.json
{
  "$schema": "./schema.json",
  "title": "Demo",
  "unit": { "name": "km", "km": 1 },
  "root": {
    "label": "Root",
    "size": 10,
    "features": [
      {
        "shape": "circle",
        "fill": { "color": "green" }
      }
    ],
    "sizePresets": [
      { "label": "1 km", "km": 1, "default": true },
      { "label": "10 km", "km": 10 },
      { "label": "100 km", "km": 100 }
    ]
  },
  "models": [
    {
      "label": "Object 1",
      "size": 20,
      "features": [
        {
          "shape": "circle",
          "outline": { "color": "red", "width": 3 }
        },
        {
          "shape": "circle",
          "radiusRatio": 0.25,
          "fill": { "color": "blue" },
          "offset": 10
        },
        {
          "shape": "circle",
          "radiusRatio": 0.25,
          "fill": { "color": "blue" },
          "offset": -10
        }
      ]
    }
  ]
}

=== pedrosbmartins/downtoearth/setup/demo-mixed-singles-groups.json
{
  "$schema": "./schema.json",
  "title": "Demo",
  "unit": { "name": "km", "km": 1 },
  "root": {
    "label": "Root",
    "size": 1,
    "features": [
      {
        "shape": "circle",
        "fill": { "color": "green" }
      }
    ],
    "sizePresets": [
      { "label": "1 km", "km": 1, "default": true },
      { "label": "10 km", "km": 10 },
      { "label": "100 km", "km": 100 }
    ]
  },
  "models": [
    {
      "label": "Object 1",
      "size": 20,
      "features": [
        {
          "shape": "circle",
          "outline": { "color": "red" }
        }
      ]
    },
    {
      "label": "Group 1",
      "bearingControl": true,
      "models": [
        {
          "label": "Grouped Object 1",
          "bearingControl": true,
          "size": 1,
          "features": [
            {
              "shape": "circle",
              "fill": { "color": "blue" },
              "drawLineToRoot": true,
              "offset": 10
            }
          ]
        },
        {
          "label": "Grouped Object 2",
          "bearingControl": true,
          "size": 1,
          "features": [
            {
              "shape": "circle",
              "fill": { "color": "blue" },
              "drawLineToRoot": true,
              "offset": -10
            }
          ]
        }
      ]
    },
    {
      "label": "Object 2",
      "size": 10,
      "features": [
        {
          "shape": "circle",
          "outline": { "color": "orange" }
        }
      ]
    },
    {
      "label": "Object 3",
      "size": 30,
      "features": [
        {
          "shape": "circle",
          "outline": { "color": "purple" }
        }
      ]
    },
    {
      "label": "Group 2",
      "bearing": 90,
      "bearingControl": true,
      "models": [
        {
          "label": "Grouped Object 1",
          "bearingControl": true,
          "size": 1,
          "features": [
            {
              "shape": "circle",
              "fill": { "color": "yellow" },
              "drawLineToRoot": true,
              "offset": 10
            }
          ]
        },
        {
          "label": "Grouped Object 2",
          "bearingControl": true,
          "size": 1,
          "features": [
            {
              "shape": "circle",
              "fill": { "color": "yellow" },
              "drawLineToRoot": true,
              "offset": -10
            }
          ]
        }
      ]
    }
  ]
}
